var svg = d3.select(".MAIN_title2")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 80)
    .attr('transform','translate(110,0)')

    svg.append('text')
    .attr('x', 470)
    .attr('y', 50)
    .text('Occurrence by type of crime')
    .style('font-size', '28px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")
    .attr("font-weight", "bolder")
