var svg = d3.select(".SUB_title2")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 60)
    .attr('transform','translate(180,0)')

    svg.append('text')
    .attr('x', 10)
    .attr('y', 50)
    .text('[ Crime occurrence frequency ]')
    .style('font-size', '20px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")

    svg.append('text')
    .attr('x', 820)
    .attr('y', 50)
    .text('[ Arrest Rate ]')
    .style('font-size', '20px')
    .attr("font-family", "sans-serif")
    .attr("fill", "black")
